inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-performance
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  # - .rubocop_rails.yml
  - .rubocop_rspec.yml
  # - .rubocop_custom.yml
  # - .rubocop_strict.yml

# Lint/DuplicateMethods:
#   Enabled: false

# AllCops:
#   NewCops: enable
    
# require: 
#   - standard

# inherit_gem:
#   standard: config/base.yml

# AllCops:
#   Exclude:
#     - "vendor/**/*"
#     - "tmp/**/*"
#     - "bin/**/*"
#     - "db/**/*"
#     - "node_modules/**/*"
#     - "storage/**/*"

# Minitest:
#   Enabled: true

