inherit_mode:
  merge:
    - Exclude

inherit_gem:
  standard: config/base.yml

require:
  - rubocop-performance
  - standard/cop/block_single_line_braces
  # - rubocop-rails
  - rubocop-rspec
  # - rubocop-minitest
  # - rubocop-rake

Lint/DuplicateMethods:
  Enabled: false
